services:
  frontend:
    build:
      context: ./UI/visualising_ham_sandwich
      args:
        - VITE_API_BASE_URL=http://localhost:5000
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./flask_backend
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    ports:
      - "5000:5000"
